#!/usr/bin/env bash

case "$XDG_SESSION_TYPE" in
"wayland")
	grim -t png -g "$(slurp)" - | tesseract stdin stdout -l "eng+rus+pol" | tr -d '\f' | wl-copy
	;;
"x11")
	maim -s -u | tesseract stdin stdout -l "eng+rus+pol" | xclip -selection clipboard
	;;
*)
	echo "Unsupported session type: $XDG_SESSION_TYPE"
	exit 1
	;;
esac
