#!/usr/bin/env bash

VIDEODIR="$HOME/Videos"
DATE_FORMAT="+%Y-%m-%d_%H-%M-%S"

if ! pgrep "wf-recorder" >/dev/null; then
	if [ ! -d "$VIDEODIR" ]; then
		mkdir -p "$VIDEODIR"
	fi
	FILENAME="$VIDEODIR/$(date --utc "$DATE_FORMAT").mp4"
	wf-recorder -f "$FILENAME" -g "$(slurp -c "#FFFFFF")" &>/dev/null &
else
	killall -s SIGINT wf-recorder
fi
