{
  lib,
  colloid-gtk-theme,
  writeText,
  flavor,
  accent,
  catppuccinColor,
}:
let
  accentMap = {
    rosewater = "pink";
    flamingo = "pink";
    pink = "pink";
    mauve = "purple";
    lavender = "purple";
    red = "red";
    maroon = "red";
    peach = "orange";
    yellow = "yellow";
    green = "green";
    teal = "teal";
    sky = "teal";
    sapphire = "teal";
    blue = "default";
  };
  themeVariant = accentMap.${accent};
  themeSuffix = lib.optionalString (themeVariant != "default") "-${lib.toSentenceCase themeVariant}";
  themeName = "Colloid${themeSuffix}-Dark-Compact-Catppuccin";

  activeSlot = if themeVariant == "default" then "blue" else themeVariant;
  slotNames = {
    red = "red";
    pink = "pink";
    purple = "mauve";
    blue = "blue";
    teal = "teal";
    green = "green";
    yellow = "yellow";
    orange = "peach";
  };
  slotColor = slot: catppuccinColor (if slot == activeSlot then accent else slotNames.${slot});
  accentLines = lib.concatLines (
    lib.mapAttrsToList (
      slot: _:
      "$" + slot + "-light: " + slotColor slot + ";\n" + "$" + slot + "-dark: " + slotColor slot + ";"
    ) slotNames
  );

  greyHex = {
    "050" = catppuccinColor "overlay2";
    "100" = catppuccinColor "overlay1";
    "150" = catppuccinColor "overlay0";
    "200" = catppuccinColor "surface2";
    "250" = catppuccinColor "surface1";
    "300" = catppuccinColor "surface0";
    "350" = catppuccinColor "surface0";
    "400" = catppuccinColor "surface0";
    "450" = catppuccinColor "surface0";
    "500" = catppuccinColor "surface0";
    "550" = catppuccinColor "surface0";
    "600" = catppuccinColor "surface0";
    "650" = catppuccinColor "surface0";
    "700" = catppuccinColor "base";
    "750" = catppuccinColor "mantle";
    "800" = catppuccinColor "crust";
    "850" = "#020202";
    "900" = "#010101";
    "950" = "#000000";
  };
  greyLines = lib.concatLines (lib.mapAttrsToList (k: v: "$grey-${k}: ${v};") greyHex);

  palette = writeText "color-palette-catppuccin.scss" ''
    // Catppuccin (${flavor}) palette - generated by nix-config
    ${accentLines}
    ${greyLines}
    $white: ${catppuccinColor "text"};
    $black: ${catppuccinColor "crust"};
    $button-close: ${catppuccinColor "red"};
    $button-max: ${catppuccinColor "green"};
    $button-min: ${catppuccinColor "yellow"};
    $links: ${catppuccinColor "sky"};
    $default-light: ${catppuccinColor accent};
    $default-dark: ${catppuccinColor accent};
  '';
in
{
  name = themeName;
  package =
    (colloid-gtk-theme.override {
      themeVariants = [ themeVariant ];
      colorVariants = [ "dark" ];
      sizeVariants = [ "compact" ];
      tweaks = [
        "catppuccin"
        "normal"
      ];
    }).overrideAttrs
      (old: {
        postPatch = (old.postPatch or "") + ''
          test -f src/sass/_color-palette-catppuccin.scss
          cp ${palette} src/sass/_color-palette-catppuccin.scss
        '';

        postInstall = (old.postInstall or "") + ''
          test -d "$out/share/themes/${themeName}"
          test -f "$out/share/themes/${themeName}/gtk-3.0/gtk.css"
          test -f "$out/share/themes/${themeName}/gtk-4.0/gtk.css"
        '';
      });
}
