{
  flake.modules.homeManager.gtk =
    {
      config,
      lib,
      pkgs,
      catppuccinColor,
      ...
    }:
    let
      inherit (config.catppuccin) accent;

      accentMap = {
        rosewater = "pink";
        flamingo = "pink";
        pink = "pink";
        mauve = "purple";
        lavender = "purple";
        red = "red";
        maroon = "red";
        peach = "orange";
        yellow = "yellow";
        green = "green";
        teal = "teal";
        sky = "teal";
        sapphire = "teal";
        blue = "default";
      };
      themeVariant = accentMap.${accent};
      themeSuffix = lib.optionalString (themeVariant != "default") "-${lib.toSentenceCase themeVariant}";

      mkCatppuccinColloid =
        { themeVariant, accent }:
        let
          activeSlot = if themeVariant == "default" then "blue" else themeVariant;
          slotNames = {
            red = "red";
            pink = "pink";
            purple = "mauve";
            blue = "blue";
            teal = "teal";
            green = "green";
            yellow = "yellow";
            orange = "peach";
          };
          slotColor = slot: catppuccinColor (if slot == activeSlot then accent else slotNames.${slot});
          accentLines = lib.concatLines (
            lib.mapAttrsToList (
              slot: _:
              "$" + slot + "-light: " + slotColor slot + ";\n" + "$" + slot + "-dark: " + slotColor slot + ";"
            ) slotNames
          );

          greyHex = {
            "050" = catppuccinColor "overlay2";
            "100" = catppuccinColor "overlay1";
            "150" = catppuccinColor "overlay0";
            "200" = catppuccinColor "surface2";
            "250" = catppuccinColor "surface1";
            "300" = catppuccinColor "surface0";
            "350" = catppuccinColor "surface0";
            "400" = catppuccinColor "surface0";
            "450" = catppuccinColor "surface0";
            "500" = catppuccinColor "surface0";
            "550" = catppuccinColor "surface0";
            "600" = catppuccinColor "surface0";
            "650" = catppuccinColor "surface0";
            "700" = catppuccinColor "base";
            "750" = catppuccinColor "mantle";
            "800" = catppuccinColor "crust";
            "850" = "#020202";
            "900" = "#010101";
            "950" = "#000000";
          };
          greyLines = lib.concatLines (lib.mapAttrsToList (k: v: "$grey-${k}: ${v};") greyHex);

          palette = pkgs.writeText "color-palette-catppuccin.scss" ''
            // Catppuccin (${config.catppuccin.flavor}) palette - generated by nix-config
            ${accentLines}
            ${greyLines}
            $white: ${catppuccinColor "text"};
            $black: ${catppuccinColor "crust"};
            $button-close: ${catppuccinColor "red"};
            $button-max: ${catppuccinColor "green"};
            $button-min: ${catppuccinColor "yellow"};
            $links: ${catppuccinColor "sky"};
            $default-light: ${catppuccinColor accent};
            $default-dark: ${catppuccinColor accent};
          '';
        in
        (pkgs.colloid-gtk-theme.override {
          themeVariants = [ themeVariant ];
          colorVariants = [ "dark" ];
          sizeVariants = [ "compact" ];
          tweaks = [
            "catppuccin"
            "normal"
          ];
        }).overrideAttrs
          (old: {
            postPatch = (old.postPatch or "") + ''
              cp ${palette} src/sass/_color-palette-catppuccin.scss
            '';
          });

      gtkTheme = {
        name = "Colloid${themeSuffix}-Dark-Compact-Catppuccin";
        package = mkCatppuccinColloid { inherit themeVariant accent; };
      };
    in
    {
      catppuccin.gtk.icon.enable = false;

      gtk = {
        enable = true;
        colorScheme = "dark";
        gtk2.force = true;
        gtk4.theme = gtkTheme;
        theme = gtkTheme;
        iconTheme = {
          inherit (config.profile.appearance.iconTheme) name package;
        };
        font = {
          name = config.profile.appearance.fonts.ui.family;
          inherit (config.profile.appearance.fonts.ui) size;
        };
        gtk3.bookmarks = [
          "file://${config.home.homeDirectory}/Documents"
          "file://${config.home.homeDirectory}/Downloads"
          "file://${config.home.homeDirectory}/Pictures"
          "file://${config.home.homeDirectory}/Videos"
        ];
      };

      dconf.settings = {
        "org/gnome/desktop/wm/preferences".button-layout = "";

        "org/gtk/gtk4/settings/file-chooser" = {
          show-hidden = true;
          view-type = "list";
        };

        "org/gtk/settings/file-chooser" = {
          date-format = "regular";
          location-mode = "path-bar";
          show-hidden = true;
          show-size-column = true;
          show-type-column = true;
          sort-column = "name";
          sort-directories-first = true;
          sort-order = "ascending";
          type-format = "category";
        };
      };
    };
}
